# -*- coding: utf-8 -*-
"""TP53_Hotspot_Scanner.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R814yA2D2UMe0eewWw3ge1EMROX43-nX
"""

# Import necessary Biopython modules for database querying and sequence parsing
from Bio import Entrez, SeqIO

# Set up NCBI connection protocol (Required by NCBI to track server usage)
Entrez.email = "akashpanda786@gmail.com"

# Define the biological accession number for the target transcript (e.g., human TP53 mRNA)
target_gene_id = "NM_000546"

print(f"Downloading Gene with ID: {target_gene_id} from NCBI.....")

# Open an active pipeline to the NCBI Nucleotide database and request the FASTA text file
handle = Entrez.efetch(db="nucleotide", id=target_gene_id, rettype="fasta", retmode="text")

# Utilize SeqIO to parse the raw text data into an organized, structural sequence record
Parsed_record = SeqIO.read(handle, "fasta")

# Close the internet connection to preserve server resources
handle.close()

# Extract the pure nucleotide sequence from the parsed record for downstream analysis
Patient_DNA = Parsed_record.seq

# Define the specific oligonucleotide sequence (probe) representing the clinical hotspot
hotspot_probe = "GGCAGCTTCGAA"

print(f"Matching the Hotspot Probe: {hotspot_probe} with Nucleotides: {len(Patient_DNA)} to find Match...")

# Scan the entire sequence transcript to find the exact coordinate index of the target probe
Matched_Coordinate = Patient_DNA.find(hotspot_probe)

# Generate an automated clinical readout based on the scan results
print("\n.......DIAGNOSTIC REPORT.......")

if Matched_Coordinate != -1:
    # If the probe is found, alert the user and provide the binding coordinate
    print(f"ALERT.....Matching Sequence {Matched_Coordinate} found with Hotspot probe: {hotspot_probe}")
else:
    # If the find() command returns -1, the sequence does not contain the target mutation
    print("\nAll Clear.....No matching sequence have been Found")